### ISSUE TITLE
warning: the folder...

### ISSUE THREAD

**Issue by RedLoreStone** [Fenixin/Minecraft-Region-Fixer#105]
C:\Users\Lorenzo Scalabrin>cd C:\Users\Lorenzo Scalabrin\Desktop\Nuova cartella (2)\Minecraft-Region-Fixer-0.3.0
C:\Users\Lorenzo Scalabrin\Desktop\Nuova cartella (2)\Minecraft-Region-Fixer-0.3.0>regionfixer.py -p 4 --delete-corrupte C:\Users\Lorenzo Scalabrin\AppData\Roaming\.minecraft\saves\redstone bc2
then i press enter and appears:
warning: the folder C:\Users\Lorenzo doesn't exit. i'll skip it.
warning: the folder Scalabrin\appdata\roaming\.minecraft\saves\redstone doesn't exit. i'll skip it.
warning: the folder bc2 doesn't exist. i'll skip it.
error: no worlds or region files to scan!

are where the error?

**Comment by Fenixin** [comment]
Hello there!

Your only problem is that you need to add quotation marks around you world folder like this:
```regionfixer.py -p 4 --delete-corrupte "C:\Users\Lorenzo Scalabrin\AppData\Roaming.minecraft\saves\redstone bc2"```

**Comment by RedLoreStone** [comment]
now it sais me this:

bug error :

<class 'typeerror'>
traceback (most recent call last):
 File "C:\Users\Lorenzo Scalabrin\Desktop\Nuova cartella (2)\Minecraft-Region-Fixer-0.3.0\regionfixer.py",  line 560,  in  <module>
      value =  main()
 File "C:\Users\Lorenzo Scalabrin\Desktop\Nuova cartella (2)\Minecraft-Region-Fixer-0.3.0\regionfixer.py",  line 343, in main
         world_list,  regionset  =  parse_paths(args)
 File "C:\Users\Lorenzo Scalabrin\Desktop\Nuova cartella (2)\Minecraft-Region-Fixer-0.3.0\regionfixer_core\world.py",  line 975, in __init__
        self.scanned_level  =  scannedDataFile(nome,  level_dat_path)
typeerror: __init__() takes from 1 to 2 positional arguments but 3 were given

**Comment by Fenixin** [comment]
Please, could you please write here the line used to run regionfixer? Also, what version of python are you usingt?

**Comment by RedLoreStone** [comment]
https://www.reddit.com/r/Minecraft/comments/bmqj8s/guide_to_fixingdeleting_corrupt_region_files/
I use the version on this page

**Comment by RedLoreStone** [comment]
what do you mean for "line used to run regionfixer"?

**Comment by RedLoreStone** [comment]
Pls can you answer? Because i really want play again in that world

**Comment by Fenixin** [comment]
You are using an old version of region-fixer. Please, download the last version from here: 

https://github.com/Fenixin/Minecraft-Region-Fixer/releases

After that it should work if you are using any 3.x python. Try and report back

**Comment by RedLoreStone** [comment]
now it works and tells me that there aren't chunck problem but the file of raids.dat and 5a66d58d-7141-44ae-a9f3-84b08baf29d2.dat (player file) are unreadable. I think that i have to remove them.
If it's correct where can i find them?

**Comment by Fenixin** [comment]
@RedLoreStone, could you please describe how did you fix it? This question has been posted many times, buen nobody says how was solved.

You can remove them, yes. That should fix whatever is happening.

**Comment by RedLoreStone** [comment]
i deleted them but minecraft still doesn't show me my world.
should i do something else?

**Comment by Fenixin** [comment]
Doesn't regionfixer report more issues?

Probably is aproblem with the new POIs, right now regionfixer can't scan them. I hope to update it soon.

**Comment by RedLoreStone** [comment]
I'll wait

**Comment by Fenixin** [comment]
Hello!

In the branch [bugfix](https://github.com/Fenixin/Minecraft-Region-Fixer/tree/bugfix) you can find a version of regionfixer that can scan poi files. Just scan the whole world directory with it and it will include poi files automatically.

I'm going to close this issue, feel free to open a new one if you have any issue. If you try this new feature, please, report back if it works or detect anything strange.
